# Java Maven CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn -B package -DskipTests=true
      - persist_to_workspace:
          root: ~/repo
          paths:
            - target/kube-funbox.jar
  push:
    docker:
     - image: docker:17.05.0-ce-git
    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker

      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: ls -lR

      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: |
          if [[ -z $CIRCLE_TAG ]]
          then
            TAG=$CIRCLE_BRANCH
          else
            TAG=$CIRCLE_TAG
          fi;
          echo $TAG;
          docker push erfangc/kube-funbox:$TAG

      - run: docker build -t erfangc/kube-funbox:$TAG .

      - run: |
          if [[ -z $CIRCLE_TAG ]]
          then
            TAG=$CIRCLE_BRANCH
          else
            TAG=$CIRCLE_TAG
          fi;
          echo $TAG;
          docker push erfangc/kube-funbox:$TAG

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - push:
          requires:
            - build

